name: studiosnap
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/dlabsign.svg
    - assets/image/splash/splashscreen_img.jpg
    - assets/image/splash/photo2.jpg
    - assets/image/self_photo/TJ1.jpg
    - assets/image/self_photo/TJ2.jpg
    - assets/image/self_photo/TJ3.jpg
    - assets/image/daniel.jpg
    - assets/icon/instagram.png
    - assets/icon/github.png
    - assets/icon/behance.png
